Add Jack Variation
rbtying/shengji pull request #466
Opened 2024-12-31 19:20 UTC by arunsrinivas20

If the trump number is J and the non-dealer team wins the last trick with a single jack, then the dealer team goes back to rank 2. All rank changes still apply **after** the rank reset occurs. It is an [optional rule](https://en.wikipedia.org/wiki/Sheng_ji#Miscellaneous_optional_rules).

The setting is located under **More Game Settings**.

<img width="631" alt="image" src="https://github.com/user-attachments/assets/aaadedd3-b2f1-4218-8639-ffa180b4c116" />

### 4-Player Jack Simulation

The dealer team (A, C) is at J and the non-dealer team (B, D) is at 9. The last trick is won by the non-dealer with a single jack . Without the variation enabled, the dealer team would advance to rank K (they kept the non-dealer team under 40 points). 

<img width="1189" alt="image" src="https://github.com/user-attachments/assets/cf782add-1814-46da-90f9-426558ba3b42" />

After clicking **Finish Game**, we will see that the jack variation will kick in. The dealer team's new rank will be 4 (see the chat box in the following screenshot), since they got sent back to rank 2, but they still held the non-dealer team under 40 points. The dealer team remains dealer. 

<img width="1663" alt="image" src="https://github.com/user-attachments/assets/33bec25d-771f-4993-b2ce-f1a9028bb0cd" />

### 5-Player Simulation

In this Finding Friends game, A (the dealer) is at J, B is at 9, C is at A, D is at J, and E is at J. C joins A during the game to form the dealer team. The last trick is won by the non-dealer team with a single jack. Without the variation, the ranks of A and C would be unchanged because they lost the round. B, E, or D would become the dealer. B, E, or D would advance to J, K, and K, respectively. 

<img width="1231" alt="image" src="https://github.com/user-attachments/assets/147568bf-a45c-4211-bc77-9c56b70dec37" />

After clicking **Finish Game**, we will see that the jack variation will kick in. A and C are sent back to rank 2 (see the chat box in the following screenshot), while the other players' ranks match what was described above. 

<img width="1669" alt="image" src="https://github.com/user-attachments/assets/de8a454c-ff8a-415f-ad40-e420425bbaf1" />

2024-12-31 19:37 UTC, arunsrinivas20 commented
@rbtying can you review this? Let me know if I'm missing something or you need clarification on the setting.

2024-12-31 21:53 UTC, rbtying requested changes
Thank you so much for working on this @arunsrinivas20 ! I'm impressed you figured this all out, I don't think I've seen you contribute before.

A number of nits in the review itself - but the main thing would be to use an enum for the setting rather than a bool because I believe there are additional variants that other folks will want to have also!

2024-12-31 21:53 UTC, rbtying commented on core/src/game_state/play_phase.rs
> +        println!("{:?}", self.trick.played_cards());
do you mind removing this? it'll clutter logs

2024-12-31 21:53 UTC, rbtying commented on core/src/game_state/play_phase.rs
> +        lost_on_single_jack: bool,
this is a bit unclear, I think (_which_ team lost on a single jack?).

Perhaps we can just pass in the last trick entirely?

2024-12-31 21:53 UTC, rbtying commented on core/src/game_state/play_phase.rs
> +        return cards.len() == 1 && cards[0].number() == Some(Number::Jack);
I've actually heard of multiple variants here, FWIW.

e.g. typically it's fine to win with a pair of J (i.e. triggers J->2), but not to win with HJHJ-J (b/c the winning requires the HJ)

2024-12-31 21:53 UTC, rbtying commented on core/src/settings.rs
> +    pub(crate) jack_variation: bool,
Due to the many ways that people play the J->2 variation - do you mind making this an enum so we can add more versions later?

```
BackToTwoSetting {
  #[default]
  Disabled,
  SingleJackToTwo,
  // AceToTwo,
}
```

2025-01-15 07:38 UTC, merged

2025-01-16 02:37 UTC, arunsrinivas20 commented
@rbtying thanks for fixing up the linting and format errors! Do you have an example of an `eslint` configuration file for next time (I couldn't run `yarn types ...` locally because of it)? Only `cargo clippy` had issues to fix on my end as a result.

2025-01-16 03:14 UTC, rbtying commented
there is a prettier config (so you can do yarn prettier —write), but I think the actual thing is that you want to be using the right version of Node so the yarn install installs the right prettier

(I’m not opposed to someone adding an eslint config but my setup doesn’t seem to need it?)